import shortid from 'shortid';

//TODO remove file
export const response = [
  {
    firstName: 'Giacomo',
    lastName: 'Guilizzoni',
    id: shortid.generate(),
    sex: '0',
    birthday: new Date(),
    temperature: 36.6,
    label: {
      name: 'Covid',
      status: 0,
      percent: 75,
    },
  },
  {
    firstName: 'Marco',
    lastName: 'Botton',
    id: shortid.generate(),
    sex: '0',
    birthday: new Date(),
    temperature: 37.2,
    label: {
      name: 'Asthma',
      status: 1,
      percent: 30,
    },
  },
  {
    firstName: 'Mariah',
    lastName: 'Malcachan',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 37.6,
    label: {
      name: 'Pregnancy',
      status: 0,
      percent: 85,
    },
  },

  {
    firstName: 'Valerie',
    lastName: 'Liberty',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.6,
    label: {
      name: 'Asthma',
      status: 2,
      percent: 40,
    },
  },
  {
    firstName: 'Giacomo',
    lastName: 'Guilizzoni',
    id: shortid.generate(),
    sex: '0',
    birthday: new Date(),
    temperature: 37.8,
    label: {
      name: 'Covid',
      status: 0,
      percent: 80,
    },
  },
  {
    firstName: 'Marco',
    lastName: 'Botton',
    id: shortid.generate(),
    sex: '0',
    birthday: new Date(),
    temperature: 36.6,
    label: {
      name: 'Pregnancy',
      status: 1,
      percent: 56,
    },
  },
  {
    firstName: 'Mariah',
    lastName: 'Malcachan',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.8,
    label: {
      name: 'Flu',
      status: 0,
      percent: 80,
    },
  },
  {
    firstName: 'Valerie',
    lastName: 'Liberty',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.6,
    label: {
      name: 'Asthma',
      status: 2,
      percent: 10,
    },
  },
  {
    firstName: 'Mariah',
    lastName: 'Malcachan',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.7,
    label: {
      name: 'Pregnancy',
      status: 0,
      percent: 90,
    },
  },
  {
    firstName: 'Valerie',
    lastName: 'Liberty',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.6,
    label: {
      name: 'Asthma',
      status: 2,
      percent: 40,
    },
  },
  {
    firstName: 'Mariah',
    lastName: 'Malcachan',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.7,
    label: {
      name: 'Pregnancy',
      status: 0,
      percent: 90,
    },
  },
  {
    firstName: 'Valerie',
    lastName: 'Liberty',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.6,
    label: {
      name: 'Asthma',
      status: 2,
      percent: 40,
    },
  },
  {
    firstName: 'Mariah',
    lastName: 'Malcachan',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.7,
    label: {
      name: 'Pregnancy',
      status: 0,
      percent: 90,
    },
  },
  {
    firstName: 'Valerie',
    lastName: 'Liberty',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.6,
    label: {
      name: 'Asthma',
      status: 2,
      percent: 40,
    },
  },
  {
    firstName: 'Mariah',
    lastName: 'Malcachan',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.7,
    label: {
      name: 'Pregnancy',
      status: 0,
      percent: 80,
    },
  },
  {
    firstName: 'Valerie',
    lastName: 'Liberty',
    id: shortid.generate(),
    sex: '1',
    birthday: new Date(),
    temperature: 36.6,
    label: {
      name: 'Asthma',
      status: 2,
      percent: 40,
    },
  },
];
